<?php

/**
 * @file
 * Contains printable.module..
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\ContentEntityTypeInterface;
use Drupal\Core\Entity\ContentEntityFormInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_entity_extra_field_info().
 */
function printable_entity_extra_field_info() {
  $extra = [];
  foreach (\Drupal::entityTypeManager()->getDefinitions() as $entity_type_id => $entity_type) {
    if ($entity_type instanceof ContentEntityTypeInterface) {
      foreach (\Drupal::entityManager()->getBundleInfo($entity_type_id) as $bundle_id => $bundle) {
        $extra[$entity_type_id][$bundle_id]['display']['_printable'] = [
          'label' => t('Print button'),
          'description' => t('Print button using printable.'),
          'weight' => 0,
          'visible' => FALSE,
        ];
        $extra[$entity_type_id][$bundle_id]['form']['_printable'] = [
          'label' => t('Print button'),
          'description' => t('Print button using printable.'),
          'weight' => 0,
          'visible' => FALSE,
        ];
      }
    }
  }

  return $extra;
}

/**
 * Implements hook_entity_view().
 */
function printable_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('_printable')) {
    $build['_printable'] = [
      '#markup' => '<a class="printable-trigger">' . t('Print this Page') . '</a>',
      '#attached' => [
        'library' => ['printable/printable'],
      ],
    ];
    $build['#attributes']['class'][] = 'printable-content';
  }
}

/**
 * Implements hook_form_alter().
 */
function printable_form_alter(array &$form, FormStateInterface $form_state) {
  $form_object = $form_state->getFormObject();
  $valid = $form_object instanceof ContentEntityFormInterface;
  if (!$valid) {
    $valid = !empty($form_object->supportsPrintable);
  }
  if ($valid) {
    $form['_printable'] = [
      '#markup' => '<a class="printable-trigger">' . t('Print this Form') . '</a>',
      '#attached' => [
        'library' => ['printable/printable'],
      ],
    ];
  }
}
